glib: Autospec creation for update from version 2.84.0 to version 2.84.1
Andika Triwidada (1):
      Update Indonesian translation

Antonio Marin (1):
      Update Romanian translation

Ask Hjorth Larsen (1):
      Updated Danish translation

Bilal Elmoussaoui (1):
      gi: Dynamically set doc-format

Danial Behzadi (1):
      Update Persian translation.

Emmanuele Bassi (1):
      docs: Document GSignalFlags members added after 2.0

Integral (1):
      gutils: make documentation of g_set_prgname() clearer

Jan Alexander Steffens (heftig) (1):
      tests: Don't install runner scripts without installed_tests

Jordi Mas (1):
      Update Catalan translation

Lukáš Tyrychtr (2):
      gio-tool: Fix handling of the trash original path
      Ensure we're printing UTF-8

Marco Trevisan (Treviño) (22):
      gobject: Be consistent in using atomic logic to handle the GParamSpecPool
      gobject: Add single function to check G_ENABLE_DIAGNOSTIC
      cancellable: Connect to cancelled signal using the ID
      girepository/compiler: Cleanup the parser on write failures
      girepository/compiler: Cleanup the parser error on failure
      girepository/parser: Clarify ownership of nodetype nodes
      gthread: Clarify when g_private_set_alloc0() suppression happens with valgrind
      gthread: Mark data allocated with g_private_set_alloc0 as leaking
      gcharset: Mark cached data as known leak
      glib/glib-private: Mark the dynamic LSAN checks as unlikely
      gio/tests/gdbus-connection: Fix typo
      gio/tests/gdbus-export: Ensure we call all the callbacks on return
      gbytes: Return early if a NULL or 0-sized GBytes is created
      gvariant: Do not byteswap empty GVariant values
      gvariant-core: Add pre-condition on variant store data being non-null
      glib/tests/gvariant: Not try to memcpy NULL data
      glib/messages: Avoid warning on potentially uninitialized value
      test/cancellable: Check that a cancellable can be unreffed on callback
      gio/cancellable: Always add reference while emitting cancelled signal
      gio/cancellable: Fix comments for g_cancellable_connect()
      gio/cancellable: Do not call data destroy function while locked
      gio/cancellable: Never call toggle notify callback in locked state

Matthias Clasen (1):
      docs: Add some detail

Philip Withnall (36):
      gsettings: Add a missing (nullable) annotation to GSettingsBindSetMapping
      gsettings: Add a missing (nullable) annotation to GSettingsGetMapping
      gsettings: Add missing (nullable) annotations to g_settings_bind_with_mapping()
      gsettings: Convert docs to gi-docgen linking syntax
      gsettings: Clarify settings types in docs
      gsettings: Improve documentation for delay-apply mode
      gsettings: Fix a minor formatting problem in get_child() docs
      build: Check for <netlink/netlink_route.h> for GNetworkMonitorNetlink
      girparser: Ignore new doc:format element in GIR files
      tests: Use g_assert_*() rather than g_assert() in properties tests
      tests: Add a test for g_object_freeze_notify() being called too often
      gfileinfo: Slightly expand docs for g_file_info_get_attribute_as_string()
      gdbusnameowning: Convert docs to gi-docgen linking syntax
      giounix-private: Fix macro for checking for epoll_create1()
      tests: Test directories inside /tmp rather than arbitrary paths
      tests: Use g_assert_*() rather than g_assert() in fileutils tests
      tests: Use standard g_test_message() logging in fileutils tests
      gfile: Document that g_file_make_directory() returns G_IO_ERROR_EXISTS
      tests: Only use g_mkstemp() in /tmp rather than current directory
      gfileutils: Clarify that g_mkstemp() and friends act in the current directory
      tests: Use g_build_filename() rather than g_strdup_printf()
      tests: Move various test paths to g_get_tmp_dir()
      gkeyfile: Better document search algorithm for g_key_file_load_from_data_dirs()
      tests: Port keyfile tests to use G_TEST_OPTION_ISOLATE_DIRS
      tests: Factor out hard-coded file names in mapping test
      tests: Port mapping tests to use G_TEST_OPTION_ISOLATE_DIRS
      tests: Add missing shell argument quoting in spawn-test
      tests: Port spawn-test tests to use G_TEST_OPTION_ISOLATE_DIRS
      gspawn-win32: Fix potential integer overflows in argv handling
      gwin32appinfo: Fix an incorrect size vs wide-length comparison
      gwin32registrykey: Clarify that value sizes are in bytes
      gwin32appinfo: Clarify some variable names
      gvarianttype: Improve docs on type validation
      tests: Fix a memory leak if a callable-info test is skipped
      girparser: Fix a strict-aliasing warning with g_clear_pointer()
      2.84.1

Sabri Ünal (1):
      Update Turkish translation

Sebastian Wilhelmi (1):
      Fix LGPL in header of gvarianttype-private.h

Vincent Chatelain (1):
      Update French translation

Overview of changes in GLib 2.84.1, 2025-04-03
==============================================

* Fix test failure when building against gobject-introspection ≥1.83.4 (#3634,
  work by Philip Withnall)

* Bugs fixed:
  - #3630 2.84.0 build failure on Linux: ../gio/gnetworkmonitornetlink.c:47:10:
    fatal error: netlink/netlink_route.h: No such file or directory (Philip
    Withnall)
  - #3634 test failure with gobject-introspection 1.83.4: warning: element
    doc:format from state 3 is unknown, ignoring (Philip Withnall)
  - #3636 gio/trash does not handle special characters well
  - #3642 `g_cancellable_connect()` documentation incorrect (Marco Trevisan
    (Treviño))

(NEWS truncated at 15 lines)