glib: Autospec creation for update from version 2.80.3 to version 2.80.4
Alexander Kanavin (1):
      girepository/introspection: correctly install .gir files into custom locations

Andy Holmes (2):
      gthreadedresolver: ref-sink returned records in lookup_records()
      tests: ensure DNS records are full-reference variants

Benjamin Otte (4):
      array: Abort on overflow
      gfile: Rewrite load_contents() to use realloc()
      tests: Use g_clear_fd()
      tests: Add test for >4GB reads with g_file_load_contents()

Philip Withnall (5):
      gioerror: Map EADDRNOTAVAIL to G_IO_ERROR_CONNECTION_REFUSED
      tests: Skip >4GB file tests unless running tests in slow/thorough mode
      tests: Improve 4GB file loading test to work on i386
      introspection: Add libgirepository as a dep to all generate_gir() calls
      2.80.4

Overview of changes in GLib 2.80.4, 2024-07-08
==============================================

* Bugs fixed:
  - #3394 GLib unit tests fail on macOS runner due to localhost being out of
    addresses (Philip Withnall)
  - #3401 Random failures to build glib 2.80.3 (Philip Withnall)
  - !4112 Backport !4111 “gioerror: Map EADDRNOTAVAIL to
    G_IO_ERROR_CONNECTION_REFUSED” to glib-2-80
  - !4118 Backport !3373 and !4117 “Handle files >4GB in g_file_load_contents()“
    to glib-2-80
  - !4124 Backport !4020 and !4122: fixes to GIR install locations and build
    race fixes
  - !4141 Backport !4110 “gthreadedresolver: ref-sink returned records in
    lookup_records()” to glib-2-80

(NEWS truncated at 15 lines)